---
config:
    debug: 2
    agent: Firefox
do:
- walk:
    to: https://www.freepeople.com/
    do:
    - find:
        path: .c-main-navigation__a--level-2
        do:
        - parse:
            attr: href
        - normalize:
            routine: url
        - link_add:
            pool: main
                
    - walk:
        to: links
        pool: main
        do:
        - find:
            path: .js-pagination__arrow--next
            do:
            - parse:
                attr: href
            - normalize:
                routine: url
            - link_add:
                pool: main
        - find:
            path: '[itemprop="product"] > [itemprop="url"]'
            do:
            - parse:
                attr: content
                filter:
                    - (.+)\?
            - normalize:
                routine: url
            - if:
                match: (\?color\=)
                else:
                - walk:
                    to: value
                    do:
                    - object_new: product
                    - variable_clear: data-sid
                    - variable_clear: data-product-id
                    - variable_clear: data-style-number
                    - variable_clear: sdecr
                    - variable_clear: fp
                    - find:
                        path: body
                        do:
                        - register_set: FreePeople
                        - object_field_set:
                            object: product
                            field: brand
                        - find: 
                            path: script:matches(product_id) 
                            do: 
                            - parse:
                                filter: 
                                    - product_style_number\s*\:\s*\[\s*\"(.+)\"\s*\]
                            - variable_set: data-style-number
                        - find: 
                            path: script:matches(product_id) 
                            do: 
                            - parse:
                                filter: 
                                    - product_id\s*\:\s*\[\s*\"(.+)\"\s*\]
                            - variable_set: styleid
                            - walk:
                                to: https://www.freepeople.com/orchestration/features/shop/?productIds=<%register%>&exclude-filter=oos-color
                                do:
                                - find: 
                                    path: product > product > parentcategory > displayname
                                    do: 
                                    - split:
                                        context: text
                                        delimiter: \>
                                    - find: 
                                        path: .splitted 
                                        do: 
                                        - parse
                                        - space_dedupe
                                        - trim
                                        - normalize:
                                            routine: lower
                                        - if:
                                            match: \S
                                            do:
                                            - object_field_set:
                                                object: product
                                                field: categories
                                                joinby: "|"
                                - find: 
                                    path: product > product  
                                    do: 
                                    - find: 
                                        path: brand 
                                        do: 
                                        - parse
                                        - space_dedupe
                                        - trim
                                        - if:
                                            match: \S
                                            do:
                                            - object_field_set:
                                                object: product
                                                field: brand
                                - find: 
                                    path: product > product > longdescription
                                    do: 
                                    - parse
                                    - space_dedupe
                                    - trim
                                    - object_field_set:
                                        object: product
                                        field: description
                                - find: 
                                    path: productmeta > stylenumber 
                                    do: 
                                    - parse
                                    - space_dedupe
                                    - trim
                                    - object_field_set:
                                        object: product
                                        field: sku
                                - find: 
                                    path: productmeta > displayname
                                    do: 
                                    - parse
                                    - space_dedupe
                                    - trim
                                    - object_field_set:
                                        object: product
                                        field: name
                                - find: 
                                    path: skuinfo > primaryslice > sliceitems
                                    do: 
                                    - variable_clear: id
                                    - find: 
                                        path: displayname 
                                        do: 
                                        - parse
                                        - space_dedupe
                                        - trim
                                        - object_field_set:
                                            object: product
                                            field: variations
                                            joinby: "|"
                                    - find: 
                                        path: id 
                                        do: 
                                        - parse
                                        - variable_set: id
                                    - find: 
                                        path: images 
                                        do: 
                                        - parse
                                        - register_set: https://images.freepeople.com/is/image/FreePeople/<%id%>_<%register%>?scl=1
                                        - object_field_set:
                                            object: product
                                            field: images
                                            joinby: "|"
                        - eval:
                            routine: js
                            body: '(function (){var d = new Date(); return d.toISOString()})();'
                        - object_field_set:
                            object: product
                            field: date
                        - static_get: url
                        - object_field_set:
                            object: product
                            field: url
                        - cookie_get: urbn_auth_payload
                        - normalize:
                            routine: replace_substring
                            args:
                                - '%20': ' '
                                - '%22': '"'
                                - '%7B': '{'
                                - '%3A': ':'
                                - '%2C': ','
                                - '%7D': '}'
                        - normalize:
                            routine: unescape_html
                        - normalize:
                            routine: json2xml
                        - to_block
                        - find:
                            path: body_safe
                            do:
                            
                            - find: 
                                path: authtoken 
                                do: 
                                - parse
                                - variable_set: auth
                            - register_set: https://www.freepeople.com/api/engage/v0/fp-us/styles/<%data-style-number%>/pictures?limit=300&offset=0&sort=heartDesc
                            - walk:
                                to: value
                                headers:
                                    X-Urbn-Auth-Token: <%auth%>
                                do:
                
                                - find:
                                    path: imageurl
                                    do:
                                    - variable_set: 
                                        field: large
                                        value: '?$fpme-style-pic-large$'
                                    - parse
                                    - normalize:
                                        routine: replace_substring
                                        args:
                                            - ^\s+|\s+$: ''
                                    - object_field_set:
                                        joinby: "|"
                                        object: product
                                        field: images
                                    - if:
                                        match: (s7w2p1.scene7.com)
                                        do:
                                        - variable_append:
                                            field: large
                                            joinby: ''
                                        - object_field_set:
                                            joinby: "|"
                                            object: product
                                            field: images
                        - find:
                            in: doc
                            path: .c-product-meta__current-price 
                            do:
                            - parse
                            - space_dedupe
                            - trim
                            - filter:
                                args:
                                    - (\d+\.\d+)\s*â€“
                                    - (\d+\.\d+)
                                    - (\d+)
                            - if:
                                match: \d
                                do:
                                - object_field_set:
                                    object: product
                                    field: price
                                    type: float
                                - register_set: USD
                                - object_field_set:
                                    object: product
                                    field: currency
                    - object_save:
                        name: product

